server:
  port: 9090 # Este microservicio va a funcionar en este puerto.

spring:
  application:
    name: msvc-course
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_course
    username: postgres
    password: alejandrobravo09
  jpa:
    hibernate:
      ddl-auto: create # Cuando le levante la app, se genera las tablas de la db automaticamente.
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka