server:
  port: 8761 # Puerto por defecto de eureka

spring:
  application:
    name: msvc-eureka # Nombre del microservicio
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost # Donde vamos a tener el servidor de eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/
