eureka: # Para que el gateway no se registre en el servidor de eureka.
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates: # Las rutas a las que se pueden redirigir
            - Path=/api/student/**
        - id: courses
          uri: http://localhost:9090
          predicates: # Las rutas a las que se pueden redirigir
            - Path=/api/course/**