server:
  port: 8090 # Este microservicio va a funcionar en este puerto.

spring:
  application:
    name: msvc-student
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_student
    username: root
    password: alejandrobravo09
  jpa:
    hibernate:
      ddl-auto: create # Cuando le levante la app, se genera las tablas de la db automaticamente.
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka